### ISSUE TITLE
Webpack compilation

### ISSUE THREAD

**Issue by LucaColonnello** [strongloop/loopback-example-react#1]
We have a problem with lbclient compilation with webpack.
In order to solve, by now I will maintain the compilation with browserify.

**Comment by LucaColonnello** [comment]
@ritch , lbclient is too big for the browser.
I know that is the same used for the Angular example, but in order to make it in a production App, have you plan to make it smaller?

**Comment by ritch** [comment]
Yes. We have plans to reduce the overhead and also an idea we talked about before was a light version of the browser bundle.

**Comment by ritch** [comment]
@bajtos has outlined some modules that (when removed) greatly reduce the bundle size of `lbclient`.

A "light" version of LoopBack in the browser would remove features duplicative of frameworks like Angular / Ember / Flux/React and simply enable you to make remote method calls.

**Comment by bajtos** [comment]
> @bajtos has outlined some modules that (when removed) greatly reduce the bundle size of lbclient.

See https://github.com/strongloop/loopback/issues/989

> A "light" version of LoopBack in the browser would remove features duplicative of frameworks like Angular / Ember / Flux/React and simply enable you to make remote method calls.

Related: https://github.com/strongloop/loopback/issues/1211

**Comment by LucaColonnello** [comment]
Ok, by now I would work with the actual version of `lbclient`.
