### ISSUE TITLE
Pull request of First Implementation

### ISSUE THREAD

**Issue by LucaColonnello** [strongloop/loopback-example-react#3]
Hi @ritch ,
I've made a pull request of a first implementation of the core with Flux and React / react-router.

Still missing the ToDo App...
If you could accept the pul reqeust I can go next and implement all the todos things...

I made this pull request to let you know the initial approach I've used.

**Comment by ritch** [comment]
Yeah the initial approach is fine. I'm not a fan of grunt or webpack, but I don't really mind if we use them. So far so good otherwise.

**Comment by LucaColonnello** [comment]
Yeah, I know. But webpack is the best tool to create SPA...
@ritch i wanna ask you if you are thinking also of a isomorphic app example with react (other than this) with Redux!!

We could also integrate GraphQL and use it with redux (that has a decorator ready to use with GraphQL)...

Let me know! We could start a training together in order to make an example like this when we have ended this example..
